apiVersion: batch/v1
kind: Job
metadata:
  name: mongoseed
spec:
  template:
    spec:
      containers:
      - name: mongoseed
        image: adevaraz/backend-test_mongoseed:latest
        env:
        - name: DB_HOST
          value: "mongodb"
        - name: DB_PORT
          value: "27017"
        - name: DB_NAME
          value: "backend-test"
      restartPolicy: Never